### ISSUE TITLE
Issue on kindle

### ISSUE THREAD

**Issue by mritunjayonemail** [jfeinstein10/SlidingMenu#400]
Hi,
I am developing an app for kindle/tablet. I created two fragment, list fragment will come in left side of screen and detail fragment will come in right side of screen.That thing is working fine.

Now i am integrating SlidingMenu using the fragments.Our app supports android 2.2.1 and forward and for fragment we are using android support library.

I took your code and generated the apklib  for the library project. Then i defined sliding menu library as dependency in my project

But  when i run 'mvn clean install' for my porject it is giving exception. Can you library project work on android version 2.2.1?

gMenu.java:[6,25] package android.annotation does not exist
[ERROR] \dev\MKumar5_BANL07R9C631C\TOM\Android\branches\Tablet\source\target\unpack\apklibs\com.slidingmenu_slidingmenu_apklib_1.3-SNAPSHOT\src\com\slidingmenu\lib\Slidin
gMenu.java:[971,2] cannot find symbol
[ERROR] symbol  : class SuppressLint
[ERROR] location: class com.slidingmenu.lib.SlidingMenu
[ERROR] \dev\MKumar5_BANL07R9C631C\TOM\Android\branches\Tablet\source\target\unpack\apklibs\com.slidingmenu_slidingmenu_apklib_1.3-SNAPSHOT\src\com\slidingmenu\lib\Slidin
gMenu.java:[987,2] cannot find symbol
[ERROR] symbol  : class TargetApi
[ERROR] location: class com.slidingmenu.lib.SlidingMenu
[ERROR] \dev\MKumar5_BANL07R9C631C\TOM\Android\branches\Tablet\source\target\unpack\apklibs\com.slidingmenu_slidingmenu_apklib_1.3-SNAPSHOT\src\com\slidingmenu\lib\Slidin
gMenu.java:[992,36] cannot find symbol
[ERROR] symbol  : variable LAYER_TYPE_HARDWARE
[ERROR] location: class android.view.View
[ERROR] \dev\MKumar5_BANL07R9C631C\TOM\Android\branches\Tablet\source\target\unpack\apklibs\com.slidingmenu_slidingmenu_apklib_1.3-SNAPSHOT\src\com\slidingmenu\lib\Slidin
gMenu.java:[992,63] cannot find symbol
[ERROR] symbol  : variable LAYER_TYPE_NONE
[ERROR] location: class android.view.View
[ERROR] \dev\MKumar5_BANL07R9C631C\TOM\Android\branches\Tablet\source\target\unpack\apklibs\com.slidingmenu_slidingmenu_apklib_1.3-SNAPSHOT\src\com\slidingmenu\lib\Slidin
gMenu.java:[994,31] cannot find symbol
[ERROR] symbol  : method getLayerType()
[ERROR] location: class android.view.View

Please suggest?

Regards,
Mritunjay

**Comment by mritunjayonemail** [comment]
Hi,

I solved this problem by commenting the honeycomb related code from SlidingMenu.java. Commented the body of function 'manageLayers' of SlidingMenu and also changed the android version to 2.2.1(same as my project version).

Now i am able to display my fragments as sliding menu. 

Is this the right approach, please let me know.

Regards,
Mritunjay
