### ISSUE TITLE
No working on android 2.3.3

### ISSUE THREAD

**Issue by thiagolocatelli** [jfeinstein10/SlidingMenu#44]
I am trying to run the app on my defy with android 2.3.3 and I keep getting this exception:

08-09 12:06:40.882: E/AndroidRuntime(12097): FATAL EXCEPTION: main
08-09 12:06:40.882: E/AndroidRuntime(12097): java.lang.NoClassDefFoundError: com.slidingmenu.example.ExampleActivity$PagerAdapter
08-09 12:06:40.882: E/AndroidRuntime(12097):    at com.slidingmenu.example.ExampleActivity.onCreate(ExampleActivity.java:29)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at android.app.ActivityThread.access$1500(ActivityThread.java:123)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at android.os.Handler.dispatchMessage(Handler.java:99)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at android.os.Looper.loop(Looper.java:130)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at android.app.ActivityThread.main(ActivityThread.java:3835)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at java.lang.reflect.Method.invokeNative(Native Method)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at java.lang.reflect.Method.invoke(Method.java:507)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
08-09 12:06:40.882: E/AndroidRuntime(12097):    at dalvik.system.NativeStart.main(Native Method)

**Comment by jfeinstein10** [comment]
Please see all the other issue reports about this

**Comment by thiagolocatelli** [comment]
I am sorry, I have just updated your library to use Sherlock action bar and I am still getting the same issue. I didnt find among your issue reports the same error. Would you mind pointing me out the solution to run on devices with previous versions? Thanks

**Comment by staber** [comment]
start with this SlidingMenu forked example if you're still having trouble implementing ABS.

https://github.com/iPaulPro/SlidingMenu

**Comment by thiagolocatelli** [comment]
Thanks a lot, I will take a look at it!

Thiago

On Fri, Aug 17, 2012 at 4:43 PM, hiv0lt notifications@github.com wrote:

> start with this SlidingMenu forked example if you're still having trouble
> implementing ABS.
> 
> https://github.com/iPaulPro/SlidingMenu
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jfeinstein10/SlidingMenu/issues/44#issuecomment-7834548.

## 

"thiago:locatelli$gmail:com".replace(':','.').replace('$','@')

**Comment by akeursten** [comment]
I had the same problem, you'll want to change the minimumsdk in the android manifest file to 11 not 1 if you are running the ExampleActivity

**Comment by jfeinstein10** [comment]
The example app has been completely redone. It is now compatible back to API level 4. Please check out the new version, there've been a lot of new features and enhancements :D

**Comment by lexer** [comment]
FATAL EXCEPTION: main
        java.lang.NoClassDefFoundError: com.slidingmenu.example.PropertiesActivity
        at com.slidingmenu.example.ExampleListActivity.onPreferenceTreeClick(ExampleListActivity.java:47)

Im using master.

**Comment by jfeinstein10** [comment]
Is your AndroidManifest correct?

**Comment by lexer** [comment]
Im trying to run sample. So i use provided AndroidManifest.

**Comment by jfeinstein10** [comment]
And you have ActionBarSherlock set up correctly?

**Comment by princeobi007** [comment]
Hi am also having the same problem 01-17 19:20:04.242: E/AndroidRuntime(3301): java.lang.NoClassDefFoundError: com.slidingmenu.lib.R$layout and i have set up my manifest correctly 2

**Comment by hwrdprkns** [comment]
This library seems to work for me on 2.3.3
